### ISSUE TITLE
Review updates

### ISSUE THREAD

**Issue by malcolmbarrett** [malcolmbarrett/metaconfoundr#5]
@JulieMOPetersen will you please review the package website (https://malcolmbarrett.github.io/metaconfoundr/) with regards to the changes made in #4? 

I'm going to start prepping for CRAN release (#6), as well, as last call for changes!

**Comment by JulieMOPetersen** [comment]
Hi @malcolmbarrett I followed the link and think it looks great! Thank you. The only things I noticed are some extra characters (maybe unicode?) in two spots: "weâll just show one" and "Please note that the âmetaconfoundrâ project "

For the Shiny App under Plot is it possible to change the checkbox to "Group by Construct" instead of "Domain"? This is the term we use in the paper and the "About" tab. Also, under the About Tab, would it be possible to carriage return each bullet under "Setting up the Data" and "Functionality and Plot Options"?

My last comment I appreciate your thoughts on. Sorry that I didn't mention this in my prior issue. We received one reviewer comment asking why we use inadequate, some concerns, and adequate instead of high risk, some concerns, and low risk. How hard would it be to add this as an option (like we have with the color scheme) and call it something like ROBINS rating labels?

**Comment by JulieMOPetersen** [comment]
Also thank you SO SO SO much for all of your hard work on this project @malcolmbarrett :)

**Comment by malcolmbarrett** [comment]
Thank you! All addressed. I'm going to prep the CRAN submission today!

**Comment by JulieMOPetersen** [comment]
Awesome, thanks, Malcolm!!
